### ISSUE TITLE
Question: Multiple oracle pool instances?

### ISSUE THREAD

**Issue by cemremengu** [jsumners/fastify-oracle#3]
Is it possible at the moment to register two oracle plugins with different names for accessing multiple oracledb instances such as in the mongodb plugin?

```
fastify
  .register(require('fastify-mongodb'), { url: 'mongodb://mongo1/mydb', name: 'MONGO1' })
  .register(require('fastify-mongodb'), { url: 'mongodb://mongo2/otherdb', name: 'MONGO2' })
```

Couldn't see anything that supports this in the code but just wanted to ask. I am going to attempt to add this feature if it is not present. What do you think?

**Comment by jsumners** [comment]
It's not something I have ever needed to do so it's not a situation I would have considered when writing the plugin. Feel free add such functionality.
